### ISSUE TITLE
In collect_data.py

### ISSUE THREAD

**Issue by kimkyeonghun** [declare-lab/WikiDes#1]
I got following error in running collect_data.py

ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.sentencizer.Sentencizer object at 0x7f9237b2e820> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

I think this is caused by the difference in the version of spacy. Can you tell me the version you use?

**Comment by hoangthangta** [comment]
Hello,
 
We used spaCy v.2.3.2. However, you can fix this error when using the latest spaCy version 3.4.1 by

```
nlp.add_pipe('sentencizer', before='parser')
```

instead of

```
nlp.add_pipe(nlp.create_pipe('sentencizer'), before='parser')
```

We updated **wiki_core.py**. Thank you for your first issue. Cheers!

**Comment by kimkyeonghun** [comment]
Thank you!
